### ISSUE TITLE
Issues raised in the morning session 

### ISSUE THREAD

**Issue by John-Kibirige** [RiyaBulia12/To-do-list#10]
Kudos @RiyaBulia12  Upon completing this milestone with the implementation of all project features with unique features like drag and drop which was really cool.  However, we were able to raise a few issues with the intention of making your code even better.

- Kindly ensure that when the user clicks on the menu, the delete icon shows up such that the user can delete a single task
- Please also try to ensure that when the user edits a task that is completed, it is unmarked (not completed or unfinished).
- You could also try avoiding using the window.reload() method 
  https://github.com/RiyaBulia12/To-do-list/blob/5124a5433cdd6a0f079bc7b728e829910e194768/src/index.js#L59
  as this is a costly process instead try rerendering the items from local storage to the UI.
- It is also good practice to stick to the ES6 syntax for functions 
  https://github.com/RiyaBulia12/To-do-list/blob/5124a5433cdd6a0f079bc7b728e829910e194768/src/index.js#L26-L29

Other than that, Happy coding  😀

**Comment by RiyaBulia12** [comment]
Thanks for the feedback @John-Kibirige and team. Addressed all the issues so closing it. :)
